mv LICENSE ..
mv README.md ..
mv babel.config.js ..
mv config ..
mv mv.sh ..
mv nohup.out ..
mv package.json ..
mv packages ..
mv scripts ..
mv setup.sh ..
mv yarn-error.log ..
mv yarn.lock ..
mv yarn.sh ..
